
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml




























rest_command:
  magicmirror_welcome:
    url: "http://192.168.50.204:8081/welcome?name={{ user | urlencode }}"
    method: GET
  welcome_api:
    url: "http://192.168.50.204:8081/welcome"
    method: POST
    content_type: "application/json"
    payload: '{"name": "{{ name | trim }}"}'
